
n              = 300                             # sample size in 1 simulated dataset
alpha1         = c(1.3, 0.3, -0.3)               # coefficient of lm(Z_1 ~ X_1 X_2) at time 1, Z_1 is set to be the BASELINE variable
alpha2         = c(  0,   0,    0)               # coefficient of lm(Z_2 ~ X_1 X_2) at time 2, set to 0 s.t. there's no other covariates besides X & BASE
alpha3         = c(  0,   0,    0)               # coefficient of lm(Z_3 ~ X_1 X_2) at time 3, set to 0 s.t. there's no other covariates besides X & BASE
beta           = c(0.3, 0.1, -0.3,  0.2,0,0 )    # coefficient of Y ~ X_1 X_2 Z_1 Z_2 Z_3 at time 3, beta[5,6] set to 0  s.t. Y is determined only by X & BASE
gamma1         = c(0.5, 0.5, -0.1,  0.3)         # coefficient of lm(A ~ X_1 X_2 Z_1) at time 1
gamma2         = c(0.5,-0.5,  0.1,  0.3)         # coefficient of lm(A ~ X_1 X_2 Z_2) at time 2    
gamma3         = c(0.2,-0.5, -0.1, -0.3)         # coefficient of lm(A ~ X_1 X_2 Z_1) at time 3, note that Z_3 has been replaced with Z_1, s.t. A is determined only by X & BASE
TrtEff_adhpbo  = 0.5                             # true treatment/causal effect in stratum [H][1]
TrtEff_adhnei  = 0                               # true treatment/causal effect in stratum [D][2]
TrtEff_adhboth = 2                               # true treatment/causal effect in stratum [I][3]
TrtEff_adhact  = 1.5                             # true treatment/causal effect in stratum [B][4]
parSave        = c("delta","S0","S1","Y0","Y1")     # List parameters to save
nSim           = 100                                # number of simulated trials
seed           = 2020
n.chains       = 2           
n.adapt        = 1000
n.burnin       = 200
n.iter         = 1000
thin           = 2
file           = "mod.txt"